# Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true

# JDK path (required for Gradle 9.1)
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableAppCompileTimeRClass=true

# AGP 9.0 built-in Kotlin support
android.builtInKotlin=true
android.newDsl=true
